version: '3'
services:
  gateway:
    build: ./services/gateway
    expose:
      - '5000'
    ports:
      - '5000:80'
    depends_on:
      - interest
      - calculate
  interest:
    build: ./services/interest
    ports:
      - '5001:80'
  calculate:
    build: ./services/calculate
    environment:
      - ASPNETCORE_INTEREST_API_URL=http://interest:80/api/taxajuros
      - ASPNETCORE_GITHUB_URL=BLABLA
    ports:
      - '5002:80'
